// Generated by gencpp from file demo1/addints.msg
// DO NOT EDIT!


#ifndef DEMO1_MESSAGE_ADDINTS_H
#define DEMO1_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <demo1/addintsRequest.h>
#include <demo1/addintsResponse.h>


namespace demo1
{

struct addints
{

typedef addintsRequest Request;
typedef addintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addints
} // namespace demo1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo1::addints > {
  static const char* value()
  {
    return "aa5e88d5a46242f3c25d5b10a656c0d2";
  }

  static const char* value(const ::demo1::addints&) { return value(); }
};

template<>
struct DataType< ::demo1::addints > {
  static const char* value()
  {
    return "demo1/addints";
  }

  static const char* value(const ::demo1::addints&) { return value(); }
};


// service_traits::MD5Sum< ::demo1::addintsRequest> should match
// service_traits::MD5Sum< ::demo1::addints >
template<>
struct MD5Sum< ::demo1::addintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo1::addints >::value();
  }
  static const char* value(const ::demo1::addintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo1::addintsRequest> should match
// service_traits::DataType< ::demo1::addints >
template<>
struct DataType< ::demo1::addintsRequest>
{
  static const char* value()
  {
    return DataType< ::demo1::addints >::value();
  }
  static const char* value(const ::demo1::addintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo1::addintsResponse> should match
// service_traits::MD5Sum< ::demo1::addints >
template<>
struct MD5Sum< ::demo1::addintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo1::addints >::value();
  }
  static const char* value(const ::demo1::addintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo1::addintsResponse> should match
// service_traits::DataType< ::demo1::addints >
template<>
struct DataType< ::demo1::addintsResponse>
{
  static const char* value()
  {
    return DataType< ::demo1::addints >::value();
  }
  static const char* value(const ::demo1::addintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO1_MESSAGE_ADDINTS_H
