// Generated by gencpp from file demo0/dd.msg
// DO NOT EDIT!


#ifndef DEMO0_MESSAGE_DD_H
#define DEMO0_MESSAGE_DD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo0
{
template <class ContainerAllocator>
struct dd_
{
  typedef dd_<ContainerAllocator> Type;

  dd_()
    : name()
    , age(0)
    , height(0.0)  {
    }
  dd_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int16_t _age_type;
  _age_type age;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::demo0::dd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo0::dd_<ContainerAllocator> const> ConstPtr;

}; // struct dd_

typedef ::demo0::dd_<std::allocator<void> > dd;

typedef boost::shared_ptr< ::demo0::dd > ddPtr;
typedef boost::shared_ptr< ::demo0::dd const> ddConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo0::dd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo0::dd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo0::dd_<ContainerAllocator1> & lhs, const ::demo0::dd_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo0::dd_<ContainerAllocator1> & lhs, const ::demo0::dd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo0::dd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo0::dd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo0::dd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo0::dd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo0::dd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo0::dd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo0::dd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0fac001a0baa828fa49ea5cc144df0e";
  }

  static const char* value(const ::demo0::dd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0fac001a0baa828ULL;
  static const uint64_t static_value2 = 0xfa49ea5cc144df0eULL;
};

template<class ContainerAllocator>
struct DataType< ::demo0::dd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo0/dd";
  }

  static const char* value(const ::demo0::dd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo0::dd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int16 age\n"
"float32 height\n"
;
  }

  static const char* value(const ::demo0::dd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo0::dd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo0::dd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo0::dd_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int16_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO0_MESSAGE_DD_H
